"""init matakuliah

Revision ID: 41c5191ff252
Revises: 49f17a2c6161
Create Date: 2025-05-15 21:04:24.483513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c5191ff252'
down_revision = '49f17a2c6161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
